function sm(){ return(map_seq(varg(argv(0,nargs())))) }
function pm(){ return(map_pch(varg(argv(0,nargs())))) }
function om(){ return(map_oct(varg(argv(0,nargs())))) }
function omrandpermu(){ return(map_oct_rnd(varg(argv(0,nargs())))) }
function pmrandpermu(){ return(map_pch_rnd(varg(argv(0,nargs())))) }
function bindev(){ return(pseudo_base(varg(argv(0,nargs())))) }
function tr(){ scopy(varg(argv(0,nargs()))) }

